//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sklad1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ запрещён! Только для администратора..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с таким артикулом уже существует!.
        /// </summary>
        internal static string ArticleExists {
            get {
                return ResourceManager.GetString("ArticleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно создана!.
        /// </summary>
        internal static string CategoryCreate {
            get {
                return ResourceManager.GetString("CategoryCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория успешно изменена!.
        /// </summary>
        internal static string CategoryEdit {
            get {
                return ResourceManager.GetString("CategoryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, выберите категорию из списка!.
        /// </summary>
        internal static string CategoryError {
            get {
                return ResourceManager.GetString("CategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория с таким названием уже существует!.
        /// </summary>
        internal static string CategoryExists {
            get {
                return ResourceManager.GetString("CategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не найдена!.
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение удаления.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранный товар?.
        /// </summary>
        internal static string ConfirmDeleteProductText {
            get {
                return ResourceManager.GetString("ConfirmDeleteProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий остаток.
        /// </summary>
        internal static string CurrentStock {
            get {
                return ResourceManager.GetString("CurrentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кириллица не допускается в адресе электронной почты!.
        /// </summary>
        internal static string CyrillicNotAllowed {
            get {
                return ResourceManager.GetString("CyrillicNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой email уже есть!.
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты должен быть от 5 до 50 символов!.
        /// </summary>
        internal static string EmailLengthError {
            get {
                return ResourceManager.GetString("EmailLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название категории!.
        /// </summary>
        internal static string EnterCategoryName {
            get {
                return ResourceManager.GetString("EnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите email и пароль!.
        /// </summary>
        internal static string EnterEmailAndPassword {
            get {
                return ResourceManager.GetString("EnterEmailAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при создании товара:.
        /// </summary>
        internal static string ErrorCreateProduct {
            get {
                return ResourceManager.GetString("ErrorCreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при создании категории.
        /// </summary>
        internal static string ErrorCreatingCategory {
            get {
                return ResourceManager.GetString("ErrorCreatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при удалении товара.
        /// </summary>
        internal static string ErrorDeletingProduct {
            get {
                return ResourceManager.GetString("ErrorDeletingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактирование категории:.
        /// </summary>
        internal static string ErrorEditCategory {
            get {
                return ResourceManager.GetString("ErrorEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактирование товара.
        /// </summary>
        internal static string ErrorEditProduct {
            get {
                return ResourceManager.GetString("ErrorEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки истории отгрузок!.
        /// </summary>
        internal static string ErrorLoadHistory {
            get {
                return ResourceManager.GetString("ErrorLoadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки товаров:.
        /// </summary>
        internal static string ErrorLoadProducts {
            get {
                return ResourceManager.GetString("ErrorLoadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при входе:.
        /// </summary>
        internal static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при регистрации:.
        /// </summary>
        internal static string ErrorRegister {
            get {
                return ResourceManager.GetString("ErrorRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка. Произошел сбой в системе!.
        /// </summary>
        internal static string ErrorSystem {
            get {
                return ResourceManager.GetString("ErrorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все поля!.
        /// </summary>
        internal static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        internal static string InitialQuantity {
            get {
                return ResourceManager.GetString("InitialQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара. .
        /// </summary>
        internal static string InsufficientStock {
            get {
                return ResourceManager.GetString("InsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при создании артикула.
        /// </summary>
        internal static string InvalidArticle {
            get {
                return ResourceManager.GetString("InvalidArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в названии категории.
        /// </summary>
        internal static string InvalidCategoryName {
            get {
                return ResourceManager.GetString("InvalidCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название получателя содержит недопустимые символы..
        /// </summary>
        internal static string InvalidClientName {
            get {
                return ResourceManager.GetString("InvalidClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный email или пароль!.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректные данные!.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный email (например, name@mail.ru)!.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО должна содержать только буквы!.
        /// </summary>
        internal static string InvalidFullName {
            get {
                return ResourceManager.GetString("InvalidFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не должен содержать эмодзи.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен быть от 6 до 50 символов!.
        /// </summary>
        internal static string InvalidPasswordLength {
            get {
                return ResourceManager.GetString("InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена должна быть положительной!.
        /// </summary>
        internal static string InvalidPositivePrice {
            get {
                return ResourceManager.GetString("InvalidPositivePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Допустимы только цифры.Попробуйте снова..
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в названии товара.
        /// </summary>
        internal static string InvalidProductName {
            get {
                return ResourceManager.GetString("InvalidProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректное количество!.
        /// </summary>
        internal static string InvalidQuantity {
            get {
                return ResourceManager.GetString("InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите выйти?.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход из аккаунта.
        /// </summary>
        internal static string LogOutText {
            get {
                return ResourceManager.GetString("LogOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО должны быть целыми строками, не содержать пробелы в середине!.
        /// </summary>
        internal static string NameHasSpaces {
            get {
                return ResourceManager.GetString("NameHasSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО должно быть от 2 до 50 символов!.
        /// </summary>
        internal static string NameLengthError {
            get {
                return ResourceManager.GetString("NameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль должен быть целой строкой, не содержать пробелы в середине!.
        /// </summary>
        internal static string PasswordHasSpaces {
            get {
                return ResourceManager.GetString("PasswordHasSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароли не совпадают!.
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно создан!.
        /// </summary>
        internal static string ProductCreate {
            get {
                return ResourceManager.GetString("ProductCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно удалён!.
        /// </summary>
        internal static string ProductDelete {
            get {
                return ResourceManager.GetString("ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар успешно изменён!.
        /// </summary>
        internal static string ProductEdit {
            get {
                return ResourceManager.GetString("ProductEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с таким названием уже существует!.
        /// </summary>
        internal static string ProductExists {
            get {
                return ResourceManager.GetString("ProductExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки товаров!.
        /// </summary>
        internal static string ProductLoadError {
            get {
                return ResourceManager.GetString("ProductLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название товара.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар с таким названием уже существует!.
        /// </summary>
        internal static string ProductNameExists {
            get {
                return ResourceManager.GetString("ProductNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена закупки.
        /// </summary>
        internal static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество .
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешна!.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар!.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при выполнении отгрузки! Проверьте остатки товаров..
        /// </summary>
        internal static string ShipmentError {
            get {
                return ResourceManager.GetString("ShipmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите получателя!.
        /// </summary>
        internal static string ShipmentNoClient {
            get {
                return ResourceManager.GetString("ShipmentNoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы один товар!.
        /// </summary>
        internal static string ShipmentNoItems {
            get {
                return ResourceManager.GetString("ShipmentNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка выполнена успешно!.
        /// </summary>
        internal static string ShipmentSuccess {
            get {
                return ResourceManager.GetString("ShipmentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий остаток.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик.
        /// </summary>
        internal static string Storekeeper {
            get {
                return ResourceManager.GetString("Storekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Складской учёт - {0}.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким email не найден!.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Неверный пароль!.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
